/*
 * This source file was generated by the Gradle 'init' task
 */

import BuildInfo.compareTo
import capabilities.resolveUrlToString
import kotlinx.serialization.json.Json
import org.schabi.newpipe.extractor.NewPipe
import org.schabi.newpipe.extractor.ServiceList
import org.schabi.newpipe.extractor.search.SearchInfo
import plugins.m3u.M3uUrlHandler
import plugins.newpipe.NextPage
import plugins.newpipe.OkHttpDownloader
import plugins.newpipe.fromJson
import plugins.newpipe.items
import plugins.rss.RssUrlHandler
import kotlin.test.Test


class AppTest {
    @Test fun testSearchNextPageDeserialization() {
        NewPipe.init(OkHttpDownloader())
        NextPage.fromJson(
            NextPage.SearchNextPage(
                "youtube",
                "linux",
                listOf("all"),
                "",
                SearchInfo.getInfo(
                    ServiceList.YouTube ,
                    ServiceList.YouTube.searchQHFactory.fromQuery("linux")
                ).nextPage
            ).toJson()
        ).items.items.take(3).let {
            println(Json.encodeToString(it))
        }
    }

    @Test fun testBackendSearch() = Backend.plugins.testSearch()

    @Test fun testPodcastIndexBasicSearch() {
        Backend.podcastindex.lists.search(Backend.podcastindex.name,"christ").let { results ->
            results.items.forEach { item ->
                println("${item.name}")
            }
            println("Next Page: ${results.nextPageToken}")
        }
    }

    @Test fun testRssUrlHandler() {
        RssUrlHandler.infoProviders[0].playlist("https://www.spreaker.com/show/6003534/episodes/feed").let {
            println("Name: ${it.name}")
            println("Description: ${it.description?.content}")
            println("Number of Episodes: ${it.items?.detailedItems?.size?:0} ")
        }
    }

    @Test fun testDownloadToString() {
        println(resolveUrlToString("https://raw.githubusercontent.com/Free-TV/IPTV/master/playlist.m3u8").length)
    }

    @Test fun testM3uUrlHandler() {
        M3uUrlHandler.infoProviders[0].playlist("https://raw.githubusercontent.com/Free-TV/IPTV/master/playlist.m3u8") .let {
            println("URL: ${it.url}")
            println("Number of items: ${it.items?.items?.size?:0} ")
        }
    }

    @Test fun testVersion() {
        assert(BuildInfo.Version(0,1,0) == BuildInfo.Version(0, 1, 0))
        assert(BuildInfo.Version(0,1,0) > BuildInfo.Version(0, 0, 0))
        assert(BuildInfo.Version(0,0,0) < BuildInfo.Version(0, 1, 0))

        assert(!(BuildInfo.Version(0,1,0) != BuildInfo.Version(0, 1, 0)))
        assert(!(BuildInfo.Version(0,1,0) <  BuildInfo.Version(0, 0, 0)))
        assert(!(BuildInfo.Version(0,0,0) >  BuildInfo.Version(0, 1, 0)))
    }

}

