import org.gradle.kotlin.dsl.support.kotlinCompilerOptions

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.1.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)
    kotlin("plugin.serialization") version "2.2.20"
//    kotlin("kapt") version "2.2.21"
	id("com.gradleup.shadow") version "9.2.2"
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
	maven { url = uri("https://jitpack.io") }
}

dependencies {
    // Use the Kotlin Test integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the JUnit 5 integration.
    testImplementation(libs.junit.jupiter.engine)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)

    implementation("com.github.TeamNewPipe:NewPipeExtractor:v0.24.8")

    // https://mvnrepository.com/artifact/org.danilopianini/khttp
    implementation("com.squareup.okhttp3:okhttp:5.2.1")

    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.9.0")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-cbor:1.9.0")

    implementation("com.github.bjoernpetersen:m3u-parser:1.4.0")

    implementation("com.github.ajalt.clikt:clikt:5.0.3")
    implementation("com.github.ajalt.clikt:clikt-markdown:5.0.3")  // optional support for rendering markdown in help messages

    implementation("org.apache.lucene:lucene-core:10.3.2")
    implementation("org.apache.lucene:lucene-analysis-icu:10.3.2")
    implementation("org.apache.lucene:lucene-queryparser:10.3.2")

    implementation("org.xerial:sqlite-jdbc:3.51.1.0")

//    implementation("info.picocli:picocli:4.7.7")
//    kapt("info.picocli:picocli-codegen:4.7.7")

    // DJL Stuff
    // https://mvnrepository.com/artifact/ai.djl/api
    implementation("ai.djl:api:0.35.1")
    implementation(platform("ai.djl:bom:0.35.1"))
    implementation("ai.djl.huggingface:tokenizers")
    runtimeOnly("ai.djl.pytorch:pytorch-engine")
    implementation("org.slf4j:slf4j-simple:2.0.17")

    implementation("org.jsoup:jsoup:1.17.2")
    implementation("org.commonmark:commonmark:0.27.0")

//    implementation(platform("ai.djl:bom:0.30.0"))
//
//    // Core DJL
//    implementation("ai.djl:api")
//
//    // PyTorch engine (used to run EmbeddingGemma)
//    implementation("ai.djl.pytorch:pytorch-engine")
//
//    // Native PyTorch runtime (CPU auto-detect)
//    implementation("ai.djl.pytorch:pytorch-native-auto")
//
//    // HuggingFace model loader
//    implementation("ai.djl.huggingface:huggingface-model-zoo")
//
//    // Tokenizers (SentencePiece, BPE, etc.)
//    implementation("ai.djl.huggingface:huggingface-tokenizers")

}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(23)
    }
}

application {
    // Define the main class for the application.
    mainClass = "AppKt"
}

distributions {
    main {
        contents {
            duplicatesStrategy = DuplicatesStrategy.EXCLUDE
        }
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
    testLogging {
        events(
            org.gradle.api.tasks.testing.logging.TestLogEvent.PASSED,
            org.gradle.api.tasks.testing.logging.TestLogEvent.SKIPPED,
            org.gradle.api.tasks.testing.logging.TestLogEvent.FAILED
        )
        exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
        showExceptions = true
        showStackTraces = true
        showCauses = true
        showStandardStreams = true  // shows println() output
    }
}

tasks.register<JavaExec>("preparePodcastIndex") {
    group = "build setup"
    description = "Converts PodcastIndex db into an Apache Luecne index as a resource."
    classpath = sourceSets["main"].runtimeClasspath
    mainClass.set("tasks.PodcastIndex")
}

tasks.register<JavaExec>("podcastSearchRepl") {
    group = null
    description = null
    standardInput = System.`in`
    classpath = sourceSets["main"].runtimeClasspath
    mainClass.set("tasks.PodcastSearchRepl")

    logging.captureStandardOutput(LogLevel.QUIET)
    logging.captureStandardError(LogLevel.QUIET)
}