import org.gradle.kotlin.dsl.support.kotlinCompilerOptions

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.1.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)
    kotlin("plugin.serialization") version "2.2.20"
//    kotlin("kapt") version "2.2.21"
	id("com.gradleup.shadow") version "9.2.2"
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
	maven { url = uri("https://jitpack.io") }
}

dependencies {
    // Use the Kotlin Test integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the JUnit 5 integration.
    testImplementation(libs.junit.jupiter.engine)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)

//    implementation("com.github.TeamNewPipe:NewPipeExtractor:v0.24.8")
    implementation("com.github.TeamNewPipe:NewPipeExtractor:v0.25.1")

    // https://mvnrepository.com/artifact/org.danilopianini/khttp
    implementation("com.squareup.okhttp3:okhttp:5.2.1")

    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.9.0")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-cbor:1.9.0")

    implementation("com.github.bjoernpetersen:m3u-parser:1.4.0")

    implementation("com.github.ajalt.clikt:clikt:5.0.3")
    implementation("com.github.ajalt.clikt:clikt-markdown:5.0.3")  // optional support for rendering markdown in help messages

    implementation("org.apache.lucene:lucene-core:10.3.2")
    implementation("org.apache.lucene:lucene-analysis-icu:10.3.2")
    implementation("org.apache.lucene:lucene-queryparser:10.3.2")

    implementation("org.xerial:sqlite-jdbc:3.51.1.0")

//    implementation("info.picocli:picocli:4.7.7")
//    kapt("info.picocli:picocli-codegen:4.7.7")

    // DJL Stuff
    // https://mvnrepository.com/artifact/ai.djl/api
    val djlVersion = "0.35.1"
    implementation("ai.djl:api:$djlVersion")
    implementation(platform("ai.djl:bom:$djlVersion"))
    implementation("ai.djl.huggingface:tokenizers:$djlVersion")

    runtimeOnly("ai.djl.pytorch:pytorch-engine")
    runtimeOnly("ai.djl.pytorch:pytorch-model-zoo")
//    // PyTorch JNI offline distribution package
    runtimeOnly("ai.djl.pytorch:pytorch-jni")
    runtimeOnly("ai.djl.pytorch:pytorch-native-cpu::linux-x86_64")




//    implementation("ai.djl.pytorch:pytorch-native-auto:$djlVersion")
//    runtimeOnly("ai.djl.pytorch:pytorch-native-cpu:2.7.1")

    implementation("org.slf4j:slf4j-simple:2.0.17")

    implementation("org.jsoup:jsoup:1.17.2")
    implementation("org.commonmark:commonmark:0.27.0")

//    implementation(platform("ai.djl:bom:0.30.0"))
//
//    // Core DJL
//    implementation("ai.djl:api")
//
//    // PyTorch engine (used to run EmbeddingGemma)
//    implementation("ai.djl.pytorch:pytorch-engine")
//
//    // Native PyTorch runtime (CPU auto-detect)
//    implementation("ai.djl.pytorch:pytorch-native-auto")
//
//    // HuggingFace model loader
//    implementation("ai.djl.huggingface:huggingface-model-zoo")
//
//    // Tokenizers (SentencePiece, BPE, etc.)
//    implementation("ai.djl.huggingface:huggingface-tokenizers")

    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.1")

    implementation("com.prof18.rssparser:rssparser:6.1.3")
    implementation("com.github.bjoernpetersen:m3u-parser:1.4.0")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(23)
    }
}

application {
    // Define the main class for the application.
    applicationName = "tuber"
    mainClass = "AppKt"
//    applicationDefaultJvmArgs += listOf("--add-modules", "jdk.incubator.vector")
}

//tasks.shadowJar {
//    mergeServiceFiles()
////    configurations = listOf(project.configurations.runtimeClasspath.get())
////    from({
////        configurations.get()
////            .filter { it.name.contains("pytorch-native") || it.name.contains("pytorch-jni") }
////            .map { zipTree(it) }
////    })
//}

//tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
//    compilerOptions {
////        languageVersion = org.jetbrains.kotlin.gradle.dsl.KotlinVersion.KOTLIN_2_0
////        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_21
//        javaParameters = true
//        freeCompilerArgs.addAll("-Xjvm-default=all", "-Xadd-modules=java.base,jdk.incubator.vector")
//    }
//}
//
//tasks.named<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>("compileTestKotlin") {
//    compilerOptions {
////        languageVersion = org.jetbrains.kotlin.gradle.dsl.KotlinVersion.KOTLIN_2_0
////        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_21
//        javaParameters = true
//        freeCompilerArgs.addAll("-Xjvm-default=all", "-Xadd-modules=java.base,jdk.incubator.vector")
//    }
//}

//kotlin {
//    compilerOptions {
//        freeCompilerArgs.addAll(listOf("-Xadd-modules=jdk.incubator.vector"))
//    }
//}

//distributions {
//    main {
//        contents {
//            duplicatesStrategy = DuplicatesStrategy.WARN
//        }
//    }
//}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()

    testLogging {
        events(
            org.gradle.api.tasks.testing.logging.TestLogEvent.PASSED,
            org.gradle.api.tasks.testing.logging.TestLogEvent.SKIPPED,
            org.gradle.api.tasks.testing.logging.TestLogEvent.FAILED
        )
        exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
        showExceptions = true
        showStackTraces = true

        /** Uncomment to show tests output in terminal */
        /*
        showCauses = true
        showStandardStreams = true  // shows println() output
        */
    }
}

tasks.register<JavaExec>("release") {
    group = "release"
    description = "create a new release on GitHub"
    classpath = sourceSets["main"].runtimeClasspath
    mainClass.set("tasks.Release")
    dependsOn("compileKotlin","compileJava","build","test")
}

//
//tasks.register<JavaExec>("podcastSearchRepl") {
//    group = null
//    description = null
//    standardInput = System.`in`
//    classpath = sourceSets["main"].runtimeClasspath
//    mainClass.set("tasks.PodcastSearchRepl")
//
//    logging.captureStandardOutput(LogLevel.QUIET)
//    logging.captureStandardError(LogLevel.QUIET)
//}