/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import OkHttpDownloader
import attemptUntilOneSucceeds
import backend
import main
import org.schabi.newpipe.extractor.NewPipe
import org.schabi.newpipe.extractor.ServiceList
import org.schabi.newpipe.extractor.search.SearchInfo
import services.Backend
import services.newpipe.*
import services.newpipe.fromJson
import java.io.FileOutputStream
import java.io.InputStream
import java.io.OutputStream
import java.io.PrintStream
import kotlin.test.Test
import kotlin.test.assertNotNull

fun withStreams(
    out : PrintStream = System.out ,
    err : PrintStream = System.err ,
    input : InputStream = System.`in` ,
    func : ()->Unit
) {

    val stdOut = System.out ; val stdErr = System.err ; val stdIn = System.`in`
    System.setOut(out) ; System.setErr(err) ; System.setIn(input)
    func()
    System.setOut(stdOut) ; System.setErr(stdErr) ; System.setIn(stdIn)
}

fun testMain(vararg args : String , testName : String) {
    withStreams (out = PrintStream(FileOutputStream("test_results/$testName")) ) {
        main(args.map{it}.toTypedArray())
    }
}

class AppTest {
    @Test fun testCLISearchYoutube() = testMain("search","youtube","linux" , testName = "youtube_search.json")
    @Test fun testCLISearchSoundCloud() = testMain("search","soundcloud","linux", testName = "soundcloud_search.json")
    @Test fun testCLISearchPeerTube() = testMain("search","peertube","linux", testName = "peertube_search.json")
//    @Test fun testCLISearchMediaCCC() = testMain("search","mediaccc","linux", testName = "mediaccc_search.json")
    @Test fun testCLISearchBandCamp() = testMain("search","bandcamp","linux", testName = "bandcamp_search.json")
    @Test fun testCLIStreamYoutube() = testMain("stream","https://www.youtube.com/watch?v=bB9z2HEldNw" , testName = "youtube_stream.json")
    @Test fun testCLIChannelYoutube() = testMain("channel","https://www.youtube.com/@TheLinuxEXP" , testName = "youtube_channel.json")
    @Test fun testCLIPlaylistYoutube() = testMain("playlist" , "https://www.youtube.com/playlist?list=PLqmbcbI8U55EQLnXs1ehDw5-D94vloCzb" , testName = "youtube_playlist.json")



    @Test fun testSearchNextPageDeserialization() {
        NewPipe.init(OkHttpDownloader())
        fromJson<NextPage>(
            NextPage.SearchNextPage(
                "youtube",
                "linux",
                listOf("all"),
                "",
                SearchInfo.getInfo(
                    ServiceList.YouTube ,
                    ServiceList.YouTube.searchQHFactory.fromQuery("linux")
                ).nextPage
            ).toJson()
        ).items.items.take(3).let {
            println(json.encodeToString(it))
        }
    }

    /*@Test fun testCLI() {
        testCLISearchYoutube()
        testCLISearchSoundCloud()
        testCLISearchPeerTube()
        testCLISearchMediaCCC()
        testCLISearchBandCamp()
        testCLIStreamYoutube()
        testCLIChannelYoutube()
        testCLIPlaylistYoutube()
    }*/

    fun red(str: String) = "\u001B[31m$str\u001B[0m"
    fun yellow(str: String) = "\u001B[93m$str\u001B[0m"
    fun green(str: String) = "\u001B[92m$str\u001B[0m"

    fun error(message : String) = println(red("Error: ") + message)
    fun warning(message : String) = println(yellow("Warning: ") + message)
    fun good(message : String) = println(green("Good: ") + message)

    fun Backend.testSearch() {
        searchProviders.map {
            try {
                it.search("linux").let { results ->
                    if(results.items.items.isEmpty()) warning("service ${it.name} search returned empty list")
                    else good("service ${it.name} search returned some results")
                    backend.moreItemsProvider.attemptUntilOneSucceeds {
                        results.items.nextPageToken?.let { token ->
                            moreItems(token)?.let{ good("Next page token is fine") }?:error("Next page token is not fine")
                        } ?: warning("Next page for search of ${it.name} is null")
                    } ?: error("Unable to get to next page for service: ${it.name}")
                }
            } catch (e:Exception) {
                error("${it.name} search threw exception: ${e.stackTraceToString()}")
                null
            }
        }
    }

    @Test fun testBackendSearch() = backend.testSearch()

}

